name: Therefore
favicon: null
layout_spectrum: 0.4322317379992455
typography_spectrum: 0.11969431256875396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6d6d6d'
    - '#9a9da1'
    - '#202020'
    - '#ac1c1c'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
