name: Therefore
favicon: null
layout_spectrum: 0.4322317379992455
typography_spectrum: 0.11969431256875396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.12856859085150063
  lightness: 0.8849555503111333
  saturation: 0.6609742457512766
  rhythmicContrast: 0.44179798010736704
purpose: []
